import secrets
from functools import wraps
from flask import session, jsonify, request
from models.user import User


def login_required(f):
    """
    Decorator that blocks unauthenticated requests with a 401.
    """
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get("user_id"):
            return jsonify({"error": "Authentication required."}), 401
        return f(*args, **kwargs)
    return decorated


def admin_required(f):
    """
    Decorator that blocks non-admins from the /admin API.

    Returns 401 when there's no session at all, and 404 (not 403) when a normal
    logged-in user hits an admin route — the portal must not even acknowledge
    its own existence to non-admins ("redirect/404 for non-admins, never expose
    it to a normal logged-in user"). Admin status is read fresh from the DB every
    request via the user's is_admin column — the single source of truth — so a
    demotion takes effect immediately, not at next login.
    """
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get("user_id"):
            return jsonify({"error": "Authentication required."}), 401
        user = get_current_user()
        if user is None or not user.is_admin:
            return jsonify({"error": "Resource not found."}), 404
        return f(*args, **kwargs)
    return decorated


def superadmin_required(f):
    """
    Gate for the few superadmin-only actions (granting/revoking the admin role).
    Same posture as admin_required but requires is_superadmin: 401 with no
    session, 404 for anyone who isn't a superadmin (including normal admins) — the
    capability stays invisible. Read live from the DB each request.
    """
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get("user_id"):
            return jsonify({"error": "Authentication required."}), 401
        user = get_current_user()
        if user is None or not user.is_superadmin:
            return jsonify({"error": "Resource not found."}), 404
        return f(*args, **kwargs)
    return decorated


def csrf_protect(f):
    """
    Decorator that verifies the X-CSRF-Token header on mutating requests.
    Apply to every POST, PUT, DELETE route that modifies data.

    The token is generated by /api/auth/csrf-token, stored in the server-side
    session, and returned in the JSON response body. The frontend stores it as
    a module-level JS variable (not a cookie, not localStorage) and sends it
    back as X-CSRF-Token on every mutating request.

    An attacker's page on another origin can trigger credentialed requests
    (the browser sends the session cookie automatically) but cannot read
    our token via CORS, so it cannot forge the X-CSRF-Token header.
    """
    @wraps(f)
    def decorated(*args, **kwargs):
        token_in_session = session.get("csrf_token")
        token_in_header  = request.headers.get("X-CSRF-Token")

        if not token_in_session or token_in_session != token_in_header:
            return jsonify({"error": "Invalid or missing CSRF token."}), 403

        return f(*args, **kwargs)
    return decorated


def get_current_user() -> User | None:
    """Returns the User for the active session, or None."""
    user_id = session.get("user_id")
    if not user_id:
        return None
    return User.get_by_id(user_id)


def set_session(user: User) -> None:
    """Writes auth payload to session after login/register."""
    session["user_id"] = user.id
    session["email"]   = user.email


def clear_session() -> None:
    """
    Clears auth data from the session while preserving the CSRF token.

    session.clear() would wipe csrf_token, leaving the frontend with a
    stale in-memory token that no longer matches the session — causing
    a 403 on the next mutating request (e.g. a second register attempt).

    We keep the CSRF token intact so the current in-memory token on the
    frontend remains valid after logout or account deletion.
    """
    csrf_token = session.get("csrf_token")
    session.clear()
    if csrf_token:
        session["csrf_token"] = csrf_token


def generate_csrf_token() -> str:
    """Generates a cryptographically secure CSRF token and stores it in session."""
    token = secrets.token_hex(32)
    session["csrf_token"] = token
    return token
