import secrets
from functools import wraps
from flask import session, jsonify, request
from models.user import User


def login_required(f):
    """
    Decorator that blocks unauthenticated requests with a 401.
    Usage:
        @bp.route("/protected")
        @login_required
        def protected():
            ...
    """
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get("user_id"):
            return jsonify({"error": "Authentication required."}), 401
        return f(*args, **kwargs)
    return decorated


def csrf_protect(f):
    """
    Decorator that verifies the X-CSRF-Token header on mutating requests.
    Apply to every POST, PUT, DELETE route that modifies data.

    The token is generated by /api/auth/csrf-token, stored in the session,
    and sent to the client as a readable cookie. The frontend reads it and
    sends it back as a header. We verify header == session value.

    This stops CSRF attacks: a malicious page on another origin can trigger
    a credentialed request (the browser sends the session cookie automatically)
    but it cannot read our CSRF cookie due to SameSite + CORS restrictions,
    so it cannot set the correct header.
    """
    @wraps(f)
    def decorated(*args, **kwargs):
        token_in_session = session.get("csrf_token")
        token_in_header  = request.headers.get("X-CSRF-Token")

        if not token_in_session or token_in_session != token_in_header:
            return jsonify({"error": "Invalid or missing CSRF token."}), 403

        return f(*args, **kwargs)
    return decorated


def get_current_user() -> User | None:
    """
    Returns the User object for the active session, or None.
    Call this inside any route that needs the full user record.
    """
    user_id = session.get("user_id")
    if not user_id:
        return None
    return User.get_by_id(user_id)


def set_session(user: User) -> None:
    """Writes the minimal session payload after login/register."""
    session["user_id"] = user.id
    session["email"]   = user.email


def clear_session() -> None:
    session.clear()


def generate_csrf_token() -> str:
    """Generates a cryptographically secure CSRF token and stores it in session."""
    token = secrets.token_hex(32)
    session["csrf_token"] = token
    return token
